import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "react-modal-video/scss/modal-video.scss";
import "swiper/css";
import "swiper/css/pagination";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import Footer from "./(webinars)/chinese-webinar/_components/footer";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/components/providers";
import { EdgeStoreProvider } from "@/lib/edgestore";

const sourceSans = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chinese Webinar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("bg-background antialiased mt-20", sourceSans.className)}
      >
        <Providers>
          <EdgeStoreProvider>
            <Navbar />
            {children}
            <Footer />
            <Toaster position="top-center" />
          </EdgeStoreProvider>
        </Providers>
      </body>
    </html>
  );
}
